myjobs/urls.py
from django.urls import include, path, re_path
from django.contrib import admin
import jobs
from jobs import views

urlpatterns = [
    # Examples:
    path('login/', jobs.views.login_view),
    re_path(r'^logout/', views.logout_view),
    re_path(r'^account/create/', jobs.views.create_account),
    re_path(r'^jobs/available', jobs.views.available_jobs),
    re_path(r'^jobs/running', jobs.views.running_jobs),
    re_path(r'^jobs/finished', jobs.views.finished_jobs),
    re_path(r'^jobs/submit', jobs.views.submit_job),
    re_path(r'^jobs/cancel', jobs.views.cancel_job),
    re_path(r'^jobs/get', jobs.views.get_job_results),
    path('', jobs.views.home_page),
    path('admin/', admin.site.urls),
]

jobs/models.py
from datetime import datetime, timedelta
from django.db import models
from django.contrib.auth.models import User

def get_upload_path(instance, filename):
  return 'user/{0}/{1}'.format(instance.user.username, filename)

def _get_expiration_date():
  return datetime.now() + timedelta(days=90);


class UserProfile(models.Model):
  user = models.OneToOneField(User, primary_key=True, default=None, on_delete=models.CASCADE)
  expiration_date = models.DateTimeField(default=_get_expiration_date)

  def __str__(self):
    return '%s->%s' % (
      self.user.username,
      self.expiration_date,
    ) 


class Job(models.Model):
  TORQUE = 'TO'
  CONDOR = 'CO'
  BACKENDS = (
    (TORQUE, 'Torque'),
    (CONDOR, 'Condor'),
  )
  name = models.CharField(max_length=250, default='', primary_key=True)
  input = models.TextField(default='')
  output = models.CharField(max_length=255, default='')
  description = models.TextField(default='')
  detailed_description = models.TextField(default='')
  host = models.GenericIPAddressField(default='0.0.0.0')
  user = models.CharField(max_length=255, default='')
  backend = models.CharField(max_length=2, choices=BACKENDS, default=TORQUE)
  job_path = models.CharField(max_length=255)  
  results_path = models.CharField(max_length=255)  
  tmp_path = models.CharField(max_length=255)  
  
  def __str__(self):
    return '%s:%s->%s@%s' % (
      self.get_backend_display(),
      self.name,
      self.user,
      self.host
    )


class RunningJob(models.Model):
  job = models.ForeignKey(Job, default=None, on_delete=models.RESTRICT)
  user = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
  timestamp = models.DateTimeField(auto_now_add=True)
  expiration_date = models.DateTimeField(default=_get_expiration_date)
  runningjob_id = models.CharField(max_length=255, default='')
  status = models.CharField(max_length=255, default='')
  input = models.FileField(upload_to=get_upload_path, default=None)
  output = models.FileField(default=None)
  notified_completed = models.BooleanField(default=False)
  notified_expiration = models.BooleanField(default=False)
  
  def __str__(self):
    return '%s %s:%s->%s' % (
      self.user,
      self.job.name,
      self.timestamp,
      self.status
    )

jobs/forms.py
from django import forms

class NewUserForm(forms.Form):
  username = forms.CharField(label='User Name',
    max_length=100,
    widget=forms.TextInput(attrs={'required':True}),
  )
  email = forms.EmailField(label='Email',
#    widget=forms.TextInput(attrs={'required':True}),
  )
  password = forms.CharField(label='Password',
    max_length=100,
    widget=forms.PasswordInput(attrs={'required':True})
  )
  confirm_password = forms.CharField(label='Confirm password',
    max_length=100,
    widget=forms.PasswordInput(attrs={'required':True})
  )


class NewJobForm(forms.Form):
  job_name = forms.CharField(label='Job Name',
    widget=forms.TextInput(attrs={'readonly':True})
  )
  job_input = forms.FileField(label='Input Files',
      widget=forms.FileInput(attrs={'required':True})
  )


class LoginForm(forms.Form):
  username = forms.CharField(label='User Name',
    max_length=100,
    widget=forms.TextInput(attrs={'required':True}),
  )
  password = forms.CharField(label='Password',
    max_length=100,
    widget=forms.PasswordInput(attrs={'required':True})
  )

jobs/views.py
import os
from datetime import datetime, timedelta

from django.conf import settings
from django.core.mail import send_mail
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect

from wsgiref.util import FileWrapper

from .forms import NewUserForm, NewJobForm, LoginForm
from .models import Job, RunningJob, UserProfile
from .drivers.JobManager import JobManager

def home_page(request):
  ''' This view shows the main page to the user.
  '''
  return render(request, 'home.html')


def login_view(request):
  ''' This view shows the login form.
  '''
  if request.method == 'POST':
    form = LoginForm(request.POST)
    if form.is_valid():
      username = request.POST['username']
      password = request.POST['password']
      user = authenticate(username=username, password=password)
      if user is not None and user.is_active:
        login(request, user)
        request.session.set_expiry(900)
        url = request.POST.get('next', '/')
        return redirect(url)
      else:
        return HttpResponse('invalid login')
  else:
    form = LoginForm()
  return render(request, 'login.html', {'form': form})


def create_account(request):
  ''' This view shows a form to create a new user account
  '''
  if request.method == 'POST':
    form = NewUserForm(request.POST)
    if form.is_valid():
      data = form.cleaned_data
      is_valid_password = (data['password'] == data['confirm_password'])
      is_valid_user = not User.objects.filter(username=data['username']).exists()
      if is_valid_password and is_valid_user:
        new_user = User.objects.create_user(
          data['username'],
          data['email'],
          data['password']
        )
        new_user.is_active = False
        new_user.save()
        new_user_profile = UserProfile.objects.create(
          user=new_user,
          expiration_date=datetime.now()+timedelta(days=365)
        )
        send_mail(
          'User account activation',
          'User ' + new_user.username + ' ask for account activation.',
          'src@mail',
          ['dst@mail']
        )
        return HttpResponse('User account created.')
#      return redirect('/')
      else:
        return render(request, 'create_account.html', {'form': form})
    else:
      return HttpResponse('Invalid request')
  else:
    form = NewUserForm()
    return render(request, 'create_account.html', {'form': form})


@login_required(login_url='/login/')
def available_jobs(request):
  ''' This view shows a list of the jobs available to the logged user
  '''
  try:
    jobs = Job.objects.all()
  except (Job.DoesNotExist, Job.MultipleObjectsReturned):
    return HttpResponse('Server Error: Invalid Job Definition')    
  return render(request, 'available_jobs.html', {'list': jobs})


@login_required(login_url='/login/')
def running_jobs(request):  
  ''' This view shows a list of the jobs the logged user has 
  already submitted.
  '''
  list_ = RunningJob.objects.filter(user=request.user)
#  for job in list_:
#    job_manager = JobManager(job)
#    job_status = job_manager.get_status()
#    if job_status != job.status:
#      job.status = job_status
#      job.save(update_fields=['status'])
  context = {
    'list': list_.exclude(status='completed'),
    'status': 'uncompleted',
  }
  return render(request, 'running_jobs.html', context)

@login_required(login_url='/login/')
def finished_jobs(request):  
  ''' This view shows a list of the jobs which are completed.
  '''
  list_ = RunningJob.objects.filter(user=request.user)
#  for job in list_:
#    job_manager = JobManager(job)
#    job_status = job_manager.get_status()
#    if job_status != job.status:
#      job.status = job_status
#      job.save(update_fields=['status'])
  context = {
    'list': list_.filter(status='completed'),
    'status': 'completed',
  }
  return render(request, 'running_jobs.html', context)


@login_required(login_url='/login/')
def submit_job(request):
  ''' This view allows the user to submit a new job to be executed.
  '''
  if request.method == 'POST':
    form = NewJobForm(request.POST, request.FILES)
    if form.is_valid():
      data = form.cleaned_data
      job_name = data['job_name']
      job_input = request.FILES['job_input']
      job = Job.objects.filter(name=job_name)[0]
      running_job = RunningJob(
        job=job,
        user=request.user,
        input=job_input,
        output=job.output,
      )
      job_manager = JobManager(running_job)
      job_manager.submit_job()
      running_job.runningjob_id = job_manager.get_job_id().strip('\n')
      if running_job.runningjob_id != '':
        running_job.save()
    return redirect('/jobs/running')
  else:
    try:
      job_name = request.GET['job_name']
      form = NewJobForm()
      form.initial = {'job_name':job_name}
    except:
      return HttpResponse('Invalid request')
    return render(request, 'submit_job.html', {'form': form})


@login_required(login_url='/login/')
def cancel_job(request):
  try:
    job_id = request.GET['job_id']
    jobs = RunningJob.objects.filter(runningjob_id=job_id, user=request.user)
    for job in jobs:
      job.delete()
  except Job.DoesNotExist:
    pass
  return redirect('/jobs/running')

import tempfile
@login_required(login_url='/login/')
def get_job_results(request):
  try:
    job_id = request.GET['job_id']
    field = request.GET['field']
    job = RunningJob.objects.get(runningjob_id=job_id)
    if field == 'job_output':
      job_manager = JobManager(job)
      tmpfile = tempfile.TemporaryFile()
      job_manager.get_results(tmpfile)
      tmpfile.seek(0)
      response = HttpResponse(tmpfile, content_type='application/zip')
      response['Content-Disposition'] = 'attachment; filename="results.zip"'
      return response
    elif field == 'job_log':
      job_manager = JobManager(job)
      tmpfile = tempfile.TemporaryFile()
      job_manager.get_log(tmpfile)
      tmpfile.seek(0)
      response = HttpResponse(tmpfile, content_type='text/plain')
      response['Content-Disposition'] = 'attachment; filename="log.txt"'
      return response
    elif field == 'job_input':
      size = os.path.getsize(job.input.path)
      wrapper = FileWrapper(job.input)
      response = HttpResponse(wrapper, content_type='text/plain')
      response['Content-Length'] = size
      return response
  except Job.DoesNotExist:
    pass
  return HttpResponse('Invalid Request')

@login_required(login_url='/login/')
def logout_view(request):
  logout(request)
  return redirect('/')

jobs/templates/available_jobs.html
<!DOCTYPE HTML>
<html>
  <head>
    <title>HPC</title>   
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static "style.css" %}" />
  </head>
  <body>
    <header>
      <img src="{% static "logo_ciemat.gif" %}" alt="CIEMAT logo" height="50" width="50" />
      <img src="{% static "logo_uned.png" %}" alt="UNED logo" height="50" width="50" />
      <h1>HPC</h1>
      {% if user.is_authenticated %}
      <nav id="id_links">
        <ul>
          <li><a href="/" id="id_home">Home</a></li>
          <li><a href="/jobs/available" id="id_available_jobs">Available Jobs</a></li>
          <li><a href="/jobs/running" id="id_running_jobs">Running Jobs</a></li>
          <li><a href="/jobs/finished" id="id_running_jobs">Finished Jobs</a></li>
          <li><a href="/logout" id="id_logout">Log out</a></li>
        </ul>
      </nav>
      <div id="id_current_user">user logged as {{ user.username }}</div>
      {% endif %}
    </header>
    <article>
      <h1>List of available jobs</h1>
      <p>These are the jobs you have available to submit.</p>
      <table id="id_available_jobs">
        <tr>
          <th></th>
          <th>Id</th>
          <th>Job Name</th>
          <th>Required Files</th>
          <th>Output</th>
          <th>Description</th>
          <th></th>
          <th></th>
        </tr>
      {% for job in list %}
        <tr>
          <td>
          <form method="GET" action="/jobs/submit">
          <button type="submit" name="job_name" value="{{ job.name }}">
            <img src="{% static "icons/play128.png" %}" alt="start {{ job.name }}" height="10" width="10" />
          </button>
          </form>
          </td>
          <td>{{ forloop.counter }}</td>
          <td>{{ job.name }}</td>
          <td>{{ job.input }}</td>
          <td>{{ job.output }}</td>
          <td>{{ job.description }}</td>
          <td>
            <a href="#" class="tooltip">
              more...
              <span>{{ job.detailed_description }}</span>
            </a>
          </td>
          <form method="GET" action="/jobs/submit">
          <td>
          <button type="submit" name="job_name" value="{{ job.name }}">
            <img src="{% static "icons/diskette18.png" %}" alt="start {{ job.name }}" height="10" width="10" />
          </button>
          </form>
          </td>
        </tr>
      {% endfor %}
      </table>
    </article>
    <!--<footer>Icons made by <a href="http://www.flaticon.com/authors/egor-rumyantsev" title="Egor Rumyantsev">Egor Rumyantsev</a> from <a href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a>             is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0">CC BY 3.0</a>-->
    </footer>
  </body>
</html>

jobs/templates/create_account.html
<!DOCTYPE HTML>
<html>
  <head>
    <title>HPC</title>   
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static "style.css" %}" />
  </head>
  <body>
    <header>
      <img src="{% static "logo_ciemat.gif" %}" alt="CIEMAT logo" height="50" width="50">
      <img src="{% static "logo_uned.png" %}" alt="UNED logo" height="50" width="50">
      <h1>HPC</h1>
      <nav id="id_links">
        <ul>
          <li><a href="/" id="id_home">Home</a></li>
        </ul>
      </nav>
    </header>
    <article>
      <h1>Fill in your data</h1>
      <p>Provide your personal data to request for an user account. Please note that your profile will not be activated until the administrator authorize your request. You will be notified to the email address provided in the form below.<p/>
      <form method="POST" action="/account/create/">
        {% csrf_token %}
        <fieldset>
          <legend>User Info</legend>
          {{ form.as_p }}
        </fieldset>
        <p class="center">
          <input class="submit" type="submit" value="create account" />
        <p>
      </form>
    </article>
  </body>
</html>

jobs/templates/home.html
<!DOCTYPE HTML>
<html>
  <head>
    <title>HPC</title>   
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static "style.css" %}" />
  </head>
  <body>
    <header>
      <img src="{% static "logo_ciemat.gif" %}" alt="CIEMAT logo" height="50" width="50">
      <img src="{% static "logo_uned.png" %}" alt="UNED logo" height="50" width="50">
      <h1>HPC</h1>
      {% if user.is_authenticated %}
      <nav id="id_links">
        <ul>
          <li><a href="/" id="id_home">Home</a></li>
          <li><a href="/jobs/available" id="id_available_jobs">Available Jobs</a></li>
          <li><a href="/jobs/running" id="id_running_jobs">Running Jobs</a></li>
          <li><a href="/jobs/finished" id="id_running_jobs">Finished Jobs</a></li>
          <li><a href="/logout" id="id_logout">Log out</a></li>
        </ul>
      </nav>
      <div id="id_current_user">user logged as: {{ user.username }}</div>
      {% else %}
      <nav id="id_links">
        <ul>
          <li><a href="/login" id="id_login">Log in</a></li>
        </ul>
      </nav>
      {% endif %}
    </header>
    <article>
      <h1>Lorem ipsum</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam at auctor nulla. Nam accumsan pretium ligula, ac luctus diam malesuada at. Quisque porttitor eros eu ante vestibulum, vel accumsan libero mattis. Aenean at sem iaculis, pharetra ipsum nec, fermentum metus. Quisque et risus leo. Nullam aliquet metus et aliquam blandit. Donec fermentum magna sit amet ex mattis ornare. Fusce ut ante risus. In hac habitasse platea dictumst. Mauris eu tortor vitae nibh bibendum laoreet sit amet at tellus. Suspendisse malesuada varius sapien, vitae ultricies lorem. Nam feugiat tortor mauris, non lacinia ligula varius vel. Donec nec justo lorem. Nulla at nibh vitae arcu faucibus ultrices eu eu est. Praesent condimentum nec mi non varius. Maecenas luctus elit sed euismod imperdiet.</p>
      <p>Aliquam eleifend varius eros, id tristique lorem facilisis et. Integer iaculis fermentum bibendum. Vestibulum tellus urna, placerat maximus libero at, eleifend imperdiet leo. Nulla sodales tincidunt velit, ac ornare magna condimentum id. Nulla augue urna, sagittis eu lacus at, elementum maximus lectus. Nullam dignissim pellentesque nulla non finibus. Nam maximus lorem sed risus imperdiet, a fermentum metus aliquet. Suspendisse quis metus eu nunc lacinia iaculis sit amet quis enim. Integer iaculis magna est, sed ultrices quam lobortis ut. Quisque metus justo, pretium id lorem blandit, ultrices maximus risus. Nam leo lorem, fringilla ut hendrerit nec, porta a eros. Donec et faucibus metus. Phasellus a ipsum sed ipsum ullamcorper interdum ac sed nisl. Curabitur sollicitudin, velit a auctor semper, ex enim dignissim dolor, finibus tempus turpis nisi et lorem.</p>
      <p>Nullam eu gravida sapien, vitae finibus sapien. Duis orci neque, rhoncus non lectus nec, tempus suscipit libero. Proin ac lectus ut nulla viverra lacinia. Cras eget orci suscipit, consectetur enim quis, commodo ligula. Pellentesque consectetur molestie lectus, sit amet rutrum risus tempor ac. Phasellus nec mauris ut massa varius vehicula vel non lacus. Proin non tempor risus, in varius tortor. Suspendisse pulvinar enim in velit tristique, at sollicitudin justo dictum. Maecenas bibendum nunc in ante ultricies molestie. Donec sit amet molestie neque. Nullam venenatis felis id rhoncus eleifend. Fusce sodales, erat pretium facilisis consectetur, velit risus hendrerit augue, quis mattis magna velit maximus nisl.</p>
      <p>Aenean ultricies lectus turpis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In mattis magna et tellus rhoncus aliquam sed vel orci. Aliquam quis blandit leo, nec semper lacus. Nulla non maximus dui. Nam non nibh risus. Etiam sed augue sit amet nisl ornare mattis nec sed est. Maecenas sit amet ex justo. Etiam posuere est libero, vel rutrum sapien suscipit sed. Sed convallis cursus ex et fermentum. Sed tempus lacinia purus, nec gravida sem eleifend non. Curabitur vel cursus lectus. Curabitur suscipit volutpat tincidunt.</p>
      <p>Morbi at convallis arcu, sed lobortis enim. Sed ornare magna ut velit gravida, faucibus faucibus tellus dapibus. Aenean ullamcorper in ante sit amet facilisis. Quisque hendrerit purus a est sollicitudin vehicula. Donec nec massa imperdiet, vulputate augue nec, sagittis sem. Aenean ultricies porttitor lacus eget dapibus. In eget consequat libero. Sed et quam ante. Suspendisse potenti. Aenean facilisis blandit bibendum.</p>
    </article>
    <footer>
      <h1 class="center">Ciemat Web<h1>
    <footer>
  </body>
</html>

jobs/templates/login.html
<!DOCTYPE HTML>
<html>
  <head>
    <title>HPC</title>   
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static "style.css" %}" />
  </head>
  <body>
    <header>
      <img src="{% static "logo_ciemat.gif" %}" alt="CIEMAT logo" height="50" width="50">
      <img src="{% static "logo_uned.png" %}" alt="UNED logo" height="50" width="50">
      <h1>HPC</h1>
      <nav id="id_links">
        <ul>
          <li><a href="/" id="id_home">Home</a></li>
        </ul>
      </nav>
    </header>
    <article>
      <h1>Sign in</h1>
      <form method="POST" action="/login/">
        <fieldset>
          <legend>Sign in with your account</legend>
          {{ form.as_p }}
        </fieldset>
        <p class="center">
          <input class="submit" type="submit" value="sign in" />
        </p>
        <p class="center">
          <a href="/account/create">Create an account</a>
        </p>
        {% csrf_token %}
      </form>
    </article>
  </body>
</html>

jobs/templates/running_jobs.html
<!DOCTYPE HTML>
<html>
  <head>
    <title>HPC</title>   
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static "style.css" %}" />
  </head>
  <body>
    <header>
      <img src="{% static "logo_ciemat.gif" %}" alt="CIEMAT logo" height="50" width="50">
      <img src="{% static "logo_uned.png" %}" alt="UNED logo" height="50" width="50">
      <h1>HPC</h1>
      {% if user.is_authenticated %}
      <nav id="id_links">
        <ul>
          <li><a href="/" id="id_home">Home</a></li>
          <li><a href="/jobs/available" id="id_available_jobs">Available Jobs</a></li>
          <li><a href="/jobs/running" id="id_running_jobs">Running Jobs</a></li>
          <li><a href="/jobs/finished" id="id_running_jobs">Finished Jobs</a></li>
          <li><a href="/logout" id="id_logout">Log out</a></li>
        </ul>
      </nav>
      <div id="id_current_user">user logged as {{ user.username }}</div>
      {% endif %}
    </header>
    <article>
      <h1>List of {{ status }} jobs</h1>
      <p>These are the jobs you have submitted.</p>
      <table id="id_running_jobs">
        <tr>
          <th></th>
          <th>Name</th>
          <th>Date</th>
          <th>Status</th>
          <th>Input</th>
          {% ifequal status "completed" %}
          <th>Results</th>
          <th>Log</th>
          {% endifequal %}
        </tr>
      {% for runningjob in list.all %}
        <tr>
          <td>
            <form method="GET" action="/jobs/cancel">
            <button type="submit" name="job_id" value="{{ runningjob.runningjob_id }}">
            <img src="{% static "icons/cancel30.png" %}" alt="cancel {{ runningjob.runningjob_id }}" height="10" widht="10" />
            </button>
            </form>
          </td>
          <td>{{ runningjob.job.name }}</td>
          <td>{{ runningjob.timestamp }}</td>
          <td>{{ runningjob.status }}</td>
          <td>
            <form method="GET" action="/jobs/get/">
            <input type="hidden" name="field" value="job_input" />
            <button type="submit" name="job_id" value="{{ runningjob.runningjob_id }}">
            <img src="{% static "icons/diskette18.png" %}" alt="start {{ runningjob.runningjob_id }}" height="10" widht="10" />
            </button>
            </form>
          </td>
          {% ifequal status "completed" %}
          <td>
            <form method="GET" action="/jobs/get">
            <input type="hidden" name="field" value="job_output" />
            <button type="submit" name="job_id" value="{{ runningjob.runningjob_id }}">
            <img src="{% static "icons/diskette18.png" %}" alt="start {{ runningjob.runningjob_id }}" height="10" widht="10" />
            </button>
            </form>
          </td>
          <td>
            <form method="GET" action="/jobs/get">
            <input type="hidden" name="field" value="job_log" />
            <button type="submit" name="job_id" value="{{ runningjob.runningjob_id }}">
            <img src="{% static "icons/diskette18.png" %}" alt="start {{ runningjob.runningjob_id }}" height="10" widht="10" />
            </button>
            </form>
          </td>
          {% endifequal %}
        </tr>
      {% endfor %}
      </table>
    </article>
  </body>
</html>

jobs/templates/submit_job.html
<!DOCTYPE HTML>
<html>
  <head>
    <title>HPC</title>   
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static "style.css" %}" />
  </head>
  <body>
    <header>
      <img src="{% static "logo_ciemat.gif" %}" alt="CIEMAT logo" height="50" width="50">
      <img src="{% static "logo_uned.png" %}" alt="UNED logo" height="50" width="50">
      <h1>HPC</h1>
      {% if user.is_authenticated %}
      <nav id="id_links">
        <ul>
          <li><a href="/" id="id_home">Home</a></li>
          <li><a href="/jobs/available" id="id_available_jobs">Available Jobs</a></li>
          <li><a href="/jobs/running" id="id_running_jobs">Running Jobs</a></li>
          <li><a href="/jobs/finished" id="id_running_jobs">Finished Jobs</a></li>
          <li><a href="/logout" id="id_logout">Log out</a></li>
        </ul>
      </nav>
      <div id="id_current_user">User: {{ user.username }}</div>
      {% endif %}
    </header>
    <article>
      <h1>Submit a new job</h1>
      <form method="POST" action="/jobs/submit/" enctype="multipart/form-data">
        <fieldset>
          <legend>User Info</legend>
          {{ form.as_p }}
          <input class="submit" type="submit" value="submit" />
        </fieldset>
        {% csrf_token %}
      </form>
      <table id="id_running_jobs">
      {% for job in list.job_set.all %}
        <tr><td>{{ forloop.counter }}: {{ job.name }}</td></tr>
      {% endfor %}
      </table>
    </article>
  </body>
</html>